apiVersion: v1
kind: Secret
metadata:
    name: iot-secrets
    namespace: flux-system
type: Opaque
stringData:
    MINIFLUX_CLIENT_SECRET: ENC[AES256_GCM,data:Yjh6GaNURIrv9Vm92QAeJVPocQmN4lrFD+uL8I/GrBN+GYJs,iv:qo8g9tBFk0MO/+3rv8WeUMsn7M+2QFYOL5jS0ZkzPCo=,tag:7KbzRWVoc+dqznJ14HMsLA==,type:str]
    MINIFLUX_PG_USER: ENC[AES256_GCM,data:BdsASPibzppCQyqy+g==,iv:YuDzlGPvZMpk7vXHWMKo8c8ZvRpLKOhgh2JbwaldlqA=,tag:qn3jfUvgBeSzEofrQ0mTiQ==,type:str]
    MINIFLUX_PG_PASSWORD: ENC[AES256_GCM,data:62IX4ju03VUUWt6+qnBxb9mhbVdd+oHNmSzYtvlgEy03NT6b,iv:nV5Swh08kpArK7bWsWPgQpvvV/UmfssQXHxQQsO+oAQ=,tag:eRIvBRb1PdrQJJyJS0jrRA==,type:str]
    HOME_ASSISTANT_CLIENT_SECRET: ENC[AES256_GCM,data:UA3TAV3N/oO+qkkjI9HPAlxvR16+HwtzvaEn+q1sJ2+ys5Ow,iv:Dw4Jm4dpVlw+aImD3JVRteUzIpI9IF2OYMCCy8eKhEg=,tag:SLV58+0/f8NivVvg4WMkcw==,type:str]
    SUPERNOTE_JWT_SECRET: ENC[AES256_GCM,data:HLESPCsL0uh1LLKGOXnBZ+OeRSLzjG88bzR2plcUYIJFriye,iv:RbeUREGTKLx4XslNVrUPTDjOBUax3Odj9xk27NDRpZ4=,tag:YkiKMTVOKffCWJe23c4TGw==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTUlmaExBSHBXWGVaU21V
            c1VDMXQwUWNwWHc3WEh6UnB3QUdLVHVKWXp3CnRPOS90L2NGdURyY1hkQ2VSNklW
            NmpiQWtIbGFFRzRNTlgwMjR0RFV6Sm8KLS0tICtCbEpoMGJpQkI1NVJOT1BYRjlw
            amJnL1g2NmZPajhCUG5ES2dWYW1VdHcKws14HEnOLJvwp6P/CGtl1KKAHk+N3XQW
            oNuuKia9oSrjpTPPk5m7/0FnJgRBe6Jpnfc1ptvnI88SNPMBIg+LXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T18:51:32Z"
    mac: ENC[AES256_GCM,data:9R7k+PsAMibQ+W2aEjqA5jg3V85ibkCyc9QCuA9BUt0/KdgU1sGsrcBkjlPKjV35mzgtgNVb0odAR1EWj4dLyhvtxM79XZo2ALPgHCI5qgEKTTZjzAINlFN1+i5GosZnEwxsxrB0bMLbCOv09tGaoVpeYRautOJhIAx3R2vPHmQ=,iv:Ntc5bdle8RX7tGE6DZ+L5+YnLpOg4Ai3aG5Xu/xZqq4=,tag:PukVm4ppWacm3TAjXlFCLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
