apiVersion: v1
kind: Secret
metadata:
    name: iot-secrets
    namespace: flux-system
type: Opaque
stringData:
    MINIFLUX_CLIENT_SECRET: ENC[AES256_GCM,data:Yjh6GaNURIrv9Vm92QAeJVPocQmN4lrFD+uL8I/GrBN+GYJs,iv:qo8g9tBFk0MO/+3rv8WeUMsn7M+2QFYOL5jS0ZkzPCo=,tag:7KbzRWVoc+dqznJ14HMsLA==,type:str]
    MINIFLUX_PG_USER: ENC[AES256_GCM,data:BdsASPibzppCQyqy+g==,iv:YuDzlGPvZMpk7vXHWMKo8c8ZvRpLKOhgh2JbwaldlqA=,tag:qn3jfUvgBeSzEofrQ0mTiQ==,type:str]
    MINIFLUX_PG_PASSWORD: ENC[AES256_GCM,data:62IX4ju03VUUWt6+qnBxb9mhbVdd+oHNmSzYtvlgEy03NT6b,iv:nV5Swh08kpArK7bWsWPgQpvvV/UmfssQXHxQQsO+oAQ=,tag:eRIvBRb1PdrQJJyJS0jrRA==,type:str]
    HOME_ASSISTANT_CLIENT_SECRET: ENC[AES256_GCM,data:UA3TAV3N/oO+qkkjI9HPAlxvR16+HwtzvaEn+q1sJ2+ys5Ow,iv:Dw4Jm4dpVlw+aImD3JVRteUzIpI9IF2OYMCCy8eKhEg=,tag:SLV58+0/f8NivVvg4WMkcw==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTUlmaExBSHBXWGVaU21V
            c1VDMXQwUWNwWHc3WEh6UnB3QUdLVHVKWXp3CnRPOS90L2NGdURyY1hkQ2VSNklW
            NmpiQWtIbGFFRzRNTlgwMjR0RFV6Sm8KLS0tICtCbEpoMGJpQkI1NVJOT1BYRjlw
            amJnL1g2NmZPajhCUG5ES2dWYW1VdHcKws14HEnOLJvwp6P/CGtl1KKAHk+N3XQW
            oNuuKia9oSrjpTPPk5m7/0FnJgRBe6Jpnfc1ptvnI88SNPMBIg+LXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:44:53Z"
    mac: ENC[AES256_GCM,data:NFfX45WkgL44UytyHAsChya/j6RgZ7zOdK4LFXwLX7Ronuqbpt85IIisZd8qTvYe0+y1YDuq1tBV11CEBIXk5wE6vXGIKR4KaQh2c1HzdjlQRtL78pWHndB3ykOXbMT5Rc3IZFojOrqYq6307ubXO3qYIi+hsxFaC0p9tY81lCM=,iv:mPDGhMxIAVRKD7PxfClcTfjuT8vYoW6p4wXzQTVfZZg=,tag:S/EM+0b2Kycixb9s2B71+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
