---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtsp-to-web
  namespace: rtsp-to-web
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: rtsp-to-web
      version: 2.2.2
  values:
    image:
      repository: ghcr.io/deepch/rtsptoweb
      tag: v2.4.3
