---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: benji
data:
  ceph.conf: |
    [global]
    mon_host = ${CEPH1_IP} ${CEPH2_IP} ${CEPH3_IP}

    [client.admin]
    keyring = /etc/ceph/keyring
