---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minecraft-proxy.yaml
  - minecraft-01-values.yaml
  - minecraft-02-values.yaml
  - minecraft-119-values.yaml
  - minecraft-05-values.yaml
  - minecraft-06-values.yaml
  - minecraft-07-values.yaml
  - minecraft-08-values.yaml
  - ../base/minecraft
