---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-02
  namespace: minecraft
spec:
  releaseName: minecraft-02
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.9.6
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    disableWait: true
  test:
    # Fix problem where helm fails to uninstall
    enable: false
  # Default values
  # https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2023.9.1
    minecraftServer:
      motd: "Woodgreen Realm / Royal Hall"
      eula: "TRUE"
      type: "PAPER"
      version: ${MINECRAFT_VERSION}
      forceReDownload: false
      onlineMode: false
      pvp: true
      ops: ${MINECRAFT_02_OPS}
      levelType: FLAT
      difficulty: hard
      gameMode: creative
      # See https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
      jvmOpts: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      memory: 4500M
      serviceType: LoadBalancer
      rcon:
        enabled: true
        password: ${RCON_PWD}
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
      SPIGET_RESOURCES: ${SPIGOT_RESOURCES},74429
      MODS: ${ESSENTIALS_URL},${COREPROTECT_URL}
    persistence:
      dataDir:
        enabled: true
    resources:
      requests:
        memory: 4500Mi
        cpu: 1000m
      limits:
        memory: 5000Mi
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc02.${DOMAIN}.
    rconServiceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc02-admin.${DOMAIN}.
