---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.gitops.weave.works
      chart: weave-gitops
      version: 4.0.36
  values:
    adminUser:
      # Use existing `cluster-user-auth` secret
      create: false
