---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  releaseName: weave-gitops
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-works
        namespace: flux-system
  interval: 5m
  # Increase default to deal with extra time needed since adding persistence
  timeout: 10m
  install:
    remediation:
      retries: 3
  test:
    enable: true
  # Default values
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: weave-gitops.${DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - weave-gitops.${DOMAIN}
    metrics:
      enabled: true
