---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: benji
resources:
  - namespace.yaml
  - release.yaml
  - backup-pvc.yaml
  - configmap.yaml
  - backup-postgres-job.yaml
