---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: supernote-backup
  namespace: supernote
spec:
  sourcePVC: supernote
  trigger:
    # Take a backup daily at 1am
    schedule: "0 1 * * *"
  restic:
    pruneIntervalDays: 14
    repository: supernote-restic-config
    retain:
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
