apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: supernote
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:ocURTu8PnKx+/qEKkJz7P21tYtIKUiSnPBRFePf2CjuqADBLUqeP9wyA/5SfU86FY9h252WsX3kanDT6WmT9xXTylylIkfE4R9fwQVGVjsI3NREwzDrmgV1aOATfoOXePMB5wYzk9F5CT7LiWEbZLUaD0UN1sVdEGbmFo+Ac9q8KDk10bqLy0yaUYRdTOJKJS3I7TBlgHrKdzMPmjJmFLk7XZ1FW7t1j9ejWTUGrYotQOlu8h03Ff0W7cdFJ0+skuaEHtyKVqH2ARmnuWHAr21KkBGdh9szgTJ6irjwPQjzLXWCX8FUOQrhR1l0RdXUGQFDmx1Blu4ZI55RBU2LllgKHD+p1u9pqpAOILM4NXSJdz3YZHqfaG4qgpNWplXZ6rXI7s14FB7yAfguGAKg7cfR1DZf/T5J501Hs9pwduS0MVbk9nyN76ovsOevpfeKyJNhPv5BT4CYD1Z1b+ucxK5i3qZ1F3Z/J,iv:8WAY+60TMDoGCf2chOaICZJUiX8jx50yHaBehHG0a/I=,tag:sqVKTQ2o8pAjSsBSyahU2Q==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRnBNa2huUkwrbjJXZjJp
            bGwyRnFzMWQ3b1E2Mzg1MnB5YVlKaUxEVEFBClhXQ05EVVdyL3JPd3RZK0tWUFZT
            TGJmZFB1cG5rYTMwOENEaVNNd2tjaEEKLS0tIE5yeWtzL3pMQmNUcGdpc25RbHlH
            Y0pRTUM1T2VuUTJzY2tWQXJIUDZiZWMKc2cEivx1Fmk52wgIoJAfuuKckRRaPIw8
            gR6EK+e3DxUVB5jb1R7i39TzrmKTJs6gdp4/fpn5xWJ6rEhHXsU8Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:53:43Z"
    mac: ENC[AES256_GCM,data:XD9flWQ6vQHZk4SJmDKqR86C1+kGd8qa5pjk2FB+dVN6N2fO98ScoaV92nnBitnSqUoQKXI9G4d6Y0TpdoT1MhpoyPWYHoQaNUSUV2n2XlSFgFX65bqdE3nmlF+3ZHieVZybFoNj1r8dzFxBM6M6z//YZ5/2UJRwy4V5Oa4R68Y=,iv:9biTlN/etCsqz73+B/IRngvlVDjX76v659ssU929Pag=,tag:BcETwVNPXbgLm4vw1gFllw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
