apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: supernote
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:TpjhzKXv6H4XWlxS51NxgLSP37x3n618eafp9Toq4RDTWPxYGrD/LqJDI3nlGZ/CY5VMSXfOvCfuuwCOm8r0P7bd5C6zXrpMcRXNL1Fadg2vEXicQHrs5tovrE0DxBPbBOEe7z+MumFJuzF4vT5eVLGidx+glM+dnS5ewLf401I/zNibkdcdapIaP2ywZDhB0jMwX44oXJZD42Rts993TDiYa1DXLbXxiHlrN0Eva7r9KrkCXWhQwqQR/6n614Q1t+HtJKakrSWT6hFUjkBUSMQ2gAgTFRdpJNjQttwJonFypp95i0IOl4c=,iv:K7Sbx+sz9T02dbMspY33Ol3AuRPaw2hd0AAHe1Q+7js=,tag:UU5KzmSfYHkG95qnbuw8Gg==,type:str]
    users.yaml: ENC[AES256_GCM,data:/bNDMcDh4mxcPKE+f2DvdlFYmypszFrrq3uFts3/Jy5PYu39wPuIO+AkSVKWHr1qjT3XTTvH59XGmByMayTGTv7sgQdeQjyUVYMfDp36QGjpzURfUDvUT1ujfcdxSwOnJt1azZ0ypO6DQTOWsFa06ZnrK4BAIqg6N6cCL7Q9lnN1opv9n0gz/sjnqi93WuJBNJSooC6SQLyOqlMXI2tox70IrlEmPpA7wbh4MoOBInb7fVEqVYdjyuPWpk4TBJned0SmAJuwh+DZdxObBONj/kmTOpNSVGbr2MojEdSHT9CQ17dy3gQkBuctCVuW4oymYjn3Z0My7hhnslYb+c2Rkbb6u1zWJlStZ80BJ40ReT2Xw/M=,iv:fawCUnjcAKzMriEiZxdrfuagYHeCFprNzi9hAkqbGWo=,tag:/E6cbTi0LtA8vU36ns1zYQ==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRnBNa2huUkwrbjJXZjJp
            bGwyRnFzMWQ3b1E2Mzg1MnB5YVlKaUxEVEFBClhXQ05EVVdyL3JPd3RZK0tWUFZT
            TGJmZFB1cG5rYTMwOENEaVNNd2tjaEEKLS0tIE5yeWtzL3pMQmNUcGdpc25RbHlH
            Y0pRTUM1T2VuUTJzY2tWQXJIUDZiZWMKc2cEivx1Fmk52wgIoJAfuuKckRRaPIw8
            gR6EK+e3DxUVB5jb1R7i39TzrmKTJs6gdp4/fpn5xWJ6rEhHXsU8Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:57:35Z"
    mac: ENC[AES256_GCM,data:ZxkvtHrcen0T2daej05b8H/PkQN82Bd9tyic+lV68qyzXnXrdJ8vBumn3CBo8zOBvDw/g5utlSdsM6ZfI0xBp57DvvIgbwa16GAC/HddKMcjxPpYBQZMMhVdV6VEZUPnX0X/MUiyzpEX01q9ZiaQaazHT6BIlhoCRzfYQ34elxQ=,iv:/y+CrL3WI4MJrc7KR5i8lCPGsyzKGcdkMGG3BTyvZm0=,tag:MzoZfTDCzVoqzkp+d7+gIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
