apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: supernote
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:vE3EpH9edayi2lZHaxbChID/TDj8g2Yv6MOFjFhDatjiHDJbM+3yIa26oYPm/WMH9XqcpKKxZaLgPcGzzNn8SYjA4PUIbEJdvwvYY3FH7BWUtKdr3fC3Hv4YkZTr3lHEs9cl6g/a3g3GDShtBckJT+0YI0DPgLh+mmaP21pod3FNkFklqNJrAoW9Nw8gvWS1IvtrJWL0rS/3TOC5ZbooTXlHfWTLjOrlH5zHgMzWoLypXFIPiG4fEiZeKaF725J8SYquoozsDM4pf/JiO9+Tz0kp2Bekftc=,iv:EffnQaXFXgn20B0NcVeHA+cMMEog4pY4oCDIgej2kio=,tag:iJnXbbiUpIRUywtWsKF6ug==,type:str]
    users.yaml: ENC[AES256_GCM,data:/bNDMcDh4mxcPKE+f2DvdlFYmypszFrrq3uFts3/Jy5PYu39wPuIO+AkSVKWHr1qjT3XTTvH59XGmByMayTGTv7sgQdeQjyUVYMfDp36QGjpzURfUDvUT1ujfcdxSwOnJt1azZ0ypO6DQTOWsFa06ZnrK4BAIqg6N6cCL7Q9lnN1opv9n0gz/sjnqi93WuJBNJSooC6SQLyOqlMXI2tox70IrlEmPpA7wbh4MoOBInb7fVEqVYdjyuPWpk4TBJned0SmAJuwh+DZdxObBONj/kmTOpNSVGbr2MojEdSHT9CQ17dy3gQkBuctCVuW4oymYjn3Z0My7hhnslYb+c2Rkbb6u1zWJlStZ80BJ40ReT2Xw/M=,iv:fawCUnjcAKzMriEiZxdrfuagYHeCFprNzi9hAkqbGWo=,tag:/E6cbTi0LtA8vU36ns1zYQ==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRnBNa2huUkwrbjJXZjJp
            bGwyRnFzMWQ3b1E2Mzg1MnB5YVlKaUxEVEFBClhXQ05EVVdyL3JPd3RZK0tWUFZT
            TGJmZFB1cG5rYTMwOENEaVNNd2tjaEEKLS0tIE5yeWtzL3pMQmNUcGdpc25RbHlH
            Y0pRTUM1T2VuUTJzY2tWQXJIUDZiZWMKc2cEivx1Fmk52wgIoJAfuuKckRRaPIw8
            gR6EK+e3DxUVB5jb1R7i39TzrmKTJs6gdp4/fpn5xWJ6rEhHXsU8Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:37:59Z"
    mac: ENC[AES256_GCM,data:L6VKb/0uFIFz+IPTY2DeZwlU/FoiBAFSGixA1Udnpmq8p1xH6tXAjj1czxrlS/iCilUgLXWs0d7vKpqkEV0HnmzlwwRq5xyC4GRX0OOLrmP1hQ98U675fBIrLl429k0ffu5NprB+tZ56G1OfVK1gOp5z5poPqs10cH+we+6E9w8=,iv:IjKgAscOmyY6CDKkn82SvNZPDH3sZF9/vIoMJeea3mA=,tag:xfMV/rd4qkXZyh1/m83OTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
