apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: supernote
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:LZjNGGSy2mVkgft+LSc4+Z+XacS0a0B/iplcB1t0o3hOiHZBpe8FVSxh4eqbbvAt8FFi+T0gEMPEYw2yRb2oAPGvnp465Bg30OBxQt64U3x6SRS3bXlcwaBujhCc7KZN4jHZxv3QZUGyg9mUTMvma/IqDP/zRv6BbLs695llly++hTsYhTyHd499DttK17c0Bz0vypH3cBKgjnYxxMiCsGXNXR7M8hmCYdSeGq3eeHjsWm7INek+U2OuYZAujZOFPj5L8wODe1JC5+n8qvP/7HB/93YaboqlFdIIDc8=,iv:AL/dz/atSv8xvY49it6Gjab5afKs336bhIzEm+SagT0=,tag:3gG0OCvcTc0FljmKZupl7Q==,type:str]
    users.yaml: ENC[AES256_GCM,data:/bNDMcDh4mxcPKE+f2DvdlFYmypszFrrq3uFts3/Jy5PYu39wPuIO+AkSVKWHr1qjT3XTTvH59XGmByMayTGTv7sgQdeQjyUVYMfDp36QGjpzURfUDvUT1ujfcdxSwOnJt1azZ0ypO6DQTOWsFa06ZnrK4BAIqg6N6cCL7Q9lnN1opv9n0gz/sjnqi93WuJBNJSooC6SQLyOqlMXI2tox70IrlEmPpA7wbh4MoOBInb7fVEqVYdjyuPWpk4TBJned0SmAJuwh+DZdxObBONj/kmTOpNSVGbr2MojEdSHT9CQ17dy3gQkBuctCVuW4oymYjn3Z0My7hhnslYb+c2Rkbb6u1zWJlStZ80BJ40ReT2Xw/M=,iv:fawCUnjcAKzMriEiZxdrfuagYHeCFprNzi9hAkqbGWo=,tag:/E6cbTi0LtA8vU36ns1zYQ==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRnBNa2huUkwrbjJXZjJp
            bGwyRnFzMWQ3b1E2Mzg1MnB5YVlKaUxEVEFBClhXQ05EVVdyL3JPd3RZK0tWUFZT
            TGJmZFB1cG5rYTMwOENEaVNNd2tjaEEKLS0tIE5yeWtzL3pMQmNUcGdpc25RbHlH
            Y0pRTUM1T2VuUTJzY2tWQXJIUDZiZWMKc2cEivx1Fmk52wgIoJAfuuKckRRaPIw8
            gR6EK+e3DxUVB5jb1R7i39TzrmKTJs6gdp4/fpn5xWJ6rEhHXsU8Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T17:55:33Z"
    mac: ENC[AES256_GCM,data:lS8FkwXRUs3lMXwJe/1uytYoppToqIyjv6tl4Z++DtIOMJo54yfuL3i+i/8QlTRxbOaiXfgOCvqswtoyo5IMhBgecRkOWTXs6YH2pXV/waqWMuMiIePspyK09z/7SWrY2UONhVeLCnqv+cZb+Ine/nJ9hdLZL0UY/Z5cDuRABL0=,iv:l0zDS53vbKH9/AkO0Z/g6qziq1oFUyG8iVaEohG9FBQ=,tag:G5wiMg5dDU0DY/KdI0vrNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
