apiVersion: v1
kind: Secret
metadata:
    name: supernote-gemini
    namespace: supernote
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:KxYo5PtY3fWUSa2cIaUI43IF4BpDms3WcrVRXNycAwgJlLP5JoKO,iv:JfR8AoxqszSWP2Mb9arA8HcjgXVSbe4C9782NhY/8ys=,tag:DsTZhXTDL4wNg8uzJiepvg==,type:str]
sops:
    age:
        - recipient: age1neakthxhftzns63tmvmpsn0rl4wfzzhsdcucm0a84et24azgxdyqrkagxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWkVONEZxZkpqZXVYU2ZW
            eUdDV04wS2R0aWdFZjZlSDVZdFMrZjJDRW04CnphZ2xFQ0g0cGo1MERkWlFNbnpi
            YkJHNVhObFR6ekJLazZVRmREYzAxSXcKLS0tIHFuR1JJbnFiNHAwcnUzMlZjM2g5
            MnNML0Znd3FIeHFuVFpEeUhYY0VKMHMKXe/hVsL7nso0gy/yc6dchNLUosaju1Be
            lecndrY7XR6rr1ryXh49hp53rn3lKZ6UghSPWrpSGB45+6+2R0BTnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T16:45:12Z"
    mac: ENC[AES256_GCM,data:ayBXAocrxTurP/GakEoGHlBxmMEZHBcRPrMivJ0CKIXe9vhejWPgIxlImvCyLdcoOfBMlfkrFomqWEpRLZkTmKMQsha1N2R9f6REwabQJ2eiBpzUyOo9nG/aJTPYosvQsY50Q3Qoe6U0R4voMXGDi80JtbE7fXGaovFlTqKuR+U=,iv:6Rqev+EjiEdzHsnuH/OT6xH/X4gbQG0YNSxATLbHGVc=,tag:BbDsv10i0zWqC5ZjmBXBGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
