---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supernote
  namespace: supernote
spec:
  releaseName: supernote
  chart:
    spec:
      chart: app-template
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      version: 4.6.2
  interval: 5m
  install:
    remediation:
      retries: 3
  test:
    # Fix problem where helm fails to uninstall
    enable: false
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        # From supernote-lite container
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/allenporter/supernote-lite
              tag: v0.13.5

            env:
              - name: SUPERNOTE_PROXY_MODE
                value: "relaxed"
              - name: SUPERNOTE_GEMINI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: supernote-gemini
                    key: api_key

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
      mcp:
        controller: main
        ports:
          http:
            port: 8081
    ingress:
      main:
        enabled: true
        className: nginx-internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: supernote.${name_service_dns_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: supernote-tls
            hosts:
              - supernote.${name_service_dns_domain}
      mcp:
        enabled: true
        className: nginx-internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: supernote-mcp.${name_service_dns_domain}
            paths:
              - path: /
                service:
                  identifier: mcp
                  port: http
        tls:
          - secretName: supernote-mcp-tls
            hosts:
              - supernote-mcp.${name_service_dns_domain}
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: ceph-block
